-- HME2 Supabase schema compatible with the current Next.js project.
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Keep updated_at fresh on row updates.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Product categories used by lib/products.ts and products filters.
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  emoji text,
  created_at timestamptz not null default now()
);

-- Products are fetched directly by the public client and joined from cart/order rows.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  category_id uuid references public.categories(id) on delete set null,
  price numeric(12, 2) not null check (price >= 0),
  original_price numeric(12, 2) check (original_price is null or original_price >= 0),
  cost numeric(12, 2) check (cost is null or cost >= 0),
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  image_url text,
  sku text unique,
  rating numeric(3, 2) not null default 0 check (rating >= 0 and rating <= 5),
  reviews_count integer not null default 0 check (reviews_count >= 0),
  specs jsonb not null default '{}'::jsonb,
  in_stock boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_is_active on public.products(is_active);

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- Persistent cart for authenticated Supabase users.
create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create index if not exists idx_cart_items_user_id on public.cart_items(user_id);
create index if not exists idx_cart_items_product_id on public.cart_items(product_id);

drop trigger if exists set_cart_items_updated_at on public.cart_items;
create trigger set_cart_items_updated_at
before update on public.cart_items
for each row execute function public.set_updated_at();

-- Orders created from the cart.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  order_number text unique,
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  shipping_address jsonb,
  billing_address jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_status on public.orders(status);

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- Order line items. The API inserts `price`, not `unit_price`, so keep this exact column.
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  price numeric(12, 2) not null check (price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);

-- Optional tables matching lib/types.ts for later account features.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  first_name text,
  last_name text,
  phone text,
  profile_image_url text,
  role text not null default 'client' check (role in ('admin', 'client')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- Enable row level security for exposed public tables.
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.profiles enable row level security;

-- Public catalog read access.
drop policy if exists "Categories are readable by everyone" on public.categories;
create policy "Categories are readable by everyone"
on public.categories for select
to anon, authenticated
using (true);

drop policy if exists "Active products are readable by everyone" on public.products;
create policy "Active products are readable by everyone"
on public.products for select
to anon, authenticated
using (is_active = true);

-- Users can access only their own cart rows.
drop policy if exists "Users can read their own cart" on public.cart_items;
create policy "Users can read their own cart"
on public.cart_items for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own cart" on public.cart_items;
create policy "Users can insert their own cart"
on public.cart_items for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own cart" on public.cart_items;
create policy "Users can update their own cart"
on public.cart_items for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own cart" on public.cart_items;
create policy "Users can delete their own cart"
on public.cart_items for delete
to authenticated
using (auth.uid() = user_id);

-- Users can access only their own orders.
drop policy if exists "Users can read their own orders" on public.orders;
create policy "Users can read their own orders"
on public.orders for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own orders" on public.orders;
create policy "Users can insert their own orders"
on public.orders for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own orders" on public.orders;
create policy "Users can update their own orders"
on public.orders for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own orders" on public.orders;
create policy "Users can delete their own orders"
on public.orders for delete
to authenticated
using (auth.uid() = user_id);

-- Order items are readable/writable only through orders owned by the user.
drop policy if exists "Users can read their own order items" on public.order_items;
create policy "Users can read their own order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

drop policy if exists "Users can insert their own order items" on public.order_items;
create policy "Users can insert their own order items"
on public.order_items for insert
to authenticated
with check (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete their own order items" on public.order_items;
create policy "Users can delete their own order items"
on public.order_items for delete
to authenticated
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

-- Profiles.
drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Grants for Supabase Data API access. RLS still controls row visibility.
grant usage on schema public to anon, authenticated;
grant select on public.categories to anon, authenticated;
grant select on public.products to anon, authenticated;
grant select, insert, update, delete on public.cart_items to authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select, insert, delete on public.order_items to authenticated;
grant select, insert, update on public.profiles to authenticated;

-- Seed categories used by the UI.
insert into public.categories (name, slug, emoji) values
  ('Cuisines', 'cuisines', '🍳'),
  ('Réfrigérateurs', 'refrigerateurs', '🧊'),
  ('Climatiseurs', 'climatiseurs', '❄️'),
  ('Lave-linges', 'lave-linges', '🧺'),
  ('Sèche-linges', 'seche-linges', '🌪️'),
  ('Fours', 'fours', '🔥'),
  ('Lave-vaisselles', 'lave-vaisselles', '🍽️'),
  ('Micro-ondes', 'micro-ondes', '🌊'),
  ('Meubles de cuisine', 'meubles-cuisine', '🪑'),
  ('Accessoires électroménagers', 'accessoires', '🔌')
on conflict (slug) do update set
  name = excluded.name,
  emoji = excluded.emoji;

-- Minimal sample products. Replace image_url values with your real assets.
insert into public.products
  (name, description, category, category_id, price, original_price, image_url, sku, rating, reviews_count, specs, in_stock)
select
  'Réfrigérateur double porte',
  'Réfrigérateur familial grande capacité.',
  c.name,
  c.id,
  1299.00,
  1499.00,
  '/images/placeholder.jpg',
  'REF-DOUBLE-001',
  4.6,
  18,
  '{"Capacité":"420 L","Classe énergétique":"A++","Garantie":"2 ans"}'::jsonb,
  true
from public.categories c
where c.slug = 'refrigerateurs'
on conflict (sku) do nothing;

insert into public.products
  (name, description, category, category_id, price, original_price, image_url, sku, rating, reviews_count, specs, in_stock)
select
  'Four encastrable électrique',
  'Four moderne avec chaleur tournante.',
  c.name,
  c.id,
  699.00,
  799.00,
  '/images/placeholder.jpg',
  'FOUR-ENCAST-001',
  4.4,
  11,
  '{"Volume":"72 L","Mode":"Chaleur tournante","Garantie":"2 ans"}'::jsonb,
  true
from public.categories c
where c.slug = 'fours'
on conflict (sku) do nothing;
